export enum UploadType {
  COMPLAINT_TYPE_IMAGE = 'COMPLAINT_TYPE_IMAGE',
  CATEGORY_IMAGE = 'CATEGORY_IMAGE',
  SUB_CATEGORY_IMAGE = 'SUB_CATEGORY_IMAGE',
  PROJECT_IMAGE = 'PROJECT_IMAGE',
  ROLE_IMAGE = 'ROLE_IMAGE',
  ADMIN_IMAGE = 'ADMIN_IMAGE',
  SUB_ADMIN_IMAGE = 'SUB_ADMIN_IMAGE',
  MESSAGE_IMAGE='MESSAGE_IMAGE',
  MESSAGE_TRAIL='MESSAGE_TRAIL',
  REOPEN_TICKET= 'REOPEN_TICKET'
}
